import {money,monthLabel,totals,categories,cashFlow,escapeHtml as esc,toCsv} from './data.js';
import {loadDashboard,isDemo,hasSession,signIn,signOut} from './services.js';
import {icon} from './icons.js';

const state={month:isDemo?'2026-10':new Date().toISOString().slice(0,7),page:'overview',data:null,hidden:false,search:'',type:'all',loading:false,error:null};
const nav=[['overview','grid','Visão geral'],['transactions','arrows','Transações'],['debts','card','Dívidas'],['reserves','shield','Reservas'],['investments','chart','Investimentos'],['insight','spark','Insight da IA']];
const colors=['#b394ff','#ed8cce','#6ddacb','#819df8','#ecc582','#666882'];
const val=n=>state.hidden?'••••••':money(n);
const pct=(a,b)=>b>0?Math.round(a/b*100):0;
const cardHead=(title,sub,action='')=>`<div class="card-head"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${action}</div>`;
const button=(label,page)=>`<button class="text-button" data-page="${page}">${label} ${icon('chevron')}</button>`;
function shell(){
 document.querySelector('#app').innerHTML=`<aside class="sidebar" id="sidebar" aria-label="Menu principal"><a class="brand" href="#overview"><span class="brand-mark">${icon('moon')}</span>luna<span class="brand-dot">.</span></a><p class="brand-caption">FINANÇAS EM EQUILÍBRIO</p><div class="workspace"><div class="avatar small">EU</div><div><strong>Meu espaço</strong><small>Finanças pessoais</small></div><span class="workspace-dot"></span></div><p class="nav-caption">PRINCIPAL</p><nav>${nav.map(([id,i,label])=>`<a href="#${id}" data-page="${id}">${icon(i)}<span>${label}</span>${id==='insight'?'<span class="tiny-badge">IA</span>':''}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="side-note">${icon('spark')}<strong>Seu futuro começa agora.</strong><p>Pequenos passos.<br>Novas possibilidades.</p></div><button data-page="settings" class="settings-button">${icon('settings')} Configurações</button><div class="profile"><div class="avatar">EU</div><div><strong>Meu dashboard</strong><small>${isDemo?'Conta de demonstração':'Conta pessoal'}</small></div></div></div></aside><button class="scrim" aria-label="Fechar menu" hidden></button><div class="main-shell"><header class="topbar"><div class="breadcrumb"><button id="menu" class="icon-button mobile-only" aria-label="Abrir menu" aria-expanded="false" aria-controls="sidebar">${icon('menu')}</button><span>Meu espaço</span><span class="slash">/</span><strong id="breadcrumb-title">Visão geral</strong></div><div class="top-actions"><span class="mode-badge"><i></i>${isDemo?'Modo demonstração':'Dados conectados'}</span><button id="privacy" class="icon-button" aria-label="Ocultar valores" aria-pressed="false">${icon('eye')}</button><div class="avatar small">EU</div></div></header><main id="main" tabindex="-1"><div class="page-heading"><div><div class="eyebrow">SEU DINHEIRO, SUAS POSSIBILIDADES</div><h1 id="page-title">Seu dinheiro. Seu futuro<span>.</span></h1><p>Clareza para hoje. Liberdade para o amanhã.</p></div><div class="heading-actions"><label class="month-control"><span class="sr-only">Período</span>${isDemo?'<select id="month" aria-label="Período"><option value="2026-10">Outubro 2026</option><option value="2026-09">Setembro 2026</option><option value="2026-08">Agosto 2026</option></select>':`<input id="month" type="month" aria-label="Período" value="${state.month}">`}</label><button id="export" class="outline-button">${icon('download')}<span>Exportar</span></button></div></div><div id="content" aria-live="polite"></div><footer><span><i class="status-dot"></i>${isDemo?'Ambiente de demonstração · valores fictícios':'Sua visão financeira pessoal'}</span><span>Luna © 2026 · Feito para o seu próximo passo</span></footer></main></div><div id="toast" role="status" class="toast" hidden></div>`;
 document.querySelector('#month').addEventListener('change',e=>{if(!e.target.value)return;state.month=e.target.value;refresh();});
 document.querySelector('#privacy').addEventListener('click',()=>{state.hidden=!state.hidden;document.querySelector('#privacy').setAttribute('aria-pressed',String(state.hidden));document.querySelector('#privacy').setAttribute('aria-label',state.hidden?'Mostrar valores':'Ocultar valores');render();});
 document.querySelector('#export').addEventListener('click',exportCsv);
 document.querySelector('#menu').addEventListener('click',()=>toggleMenu());
 document.querySelector('.scrim').addEventListener('click',()=>toggleMenu(false));
 document.addEventListener('keydown',e=>{if(e.key==='Escape')toggleMenu(false);});
 document.addEventListener('click',e=>{const target=e.target.closest('[data-page]');if(target){e.preventDefault();location.hash=target.dataset.page;toggleMenu(false);}});
 window.addEventListener('hashchange',route);
 route();
}
function toggleMenu(open=!document.querySelector('.sidebar').classList.contains('open')){document.querySelector('.sidebar').classList.toggle('open',open);document.querySelector('.scrim').hidden=!open;document.querySelector('#menu').setAttribute('aria-expanded',String(open));}
function route(){const requested=location.hash.slice(1);state.page=[...nav.map(n=>n[0]),'settings'].includes(requested)?requested:'overview';render();}
function kpis(){const t=totals(state.data);return `<section class="kpi-grid" aria-label="Resumo financeiro">${[
 ['Saldo disponível',t.balance,'wallet','violet','Seu saldo no período'],['Receitas do mês',t.income,'up','mint','Entradas registradas'],['Despesas do mês',t.expenses,'down','pink','Saídas registradas'],['Dívidas em aberto',t.debts,'card','peach',`${state.data.debts.length} compromissos ativos`]
 ].map(([label,value,i,color,sub],idx)=>`<article class="kpi ${idx===0?'featured':''}"><div class="kpi-top"><span>${label}</span><span class="icon-tile ${color}">${icon(i)}</span></div><strong>${val(value)}</strong><div class="kpi-bottom"><span class="${color}">${idx===0?'●':idx===1?'↗':idx===2?'↘':'○'}</span> ${sub}</div><svg class="mini-spark ${color}" viewBox="0 0 90 28" aria-hidden="true"><path d="M1 25 14 18 26 21 39 12 52 17 65 8 78 11 89 2"/></svg></article>`).join('')}</section>`;}
function flowChart(){
 const rows=cashFlow(state.data),max=Math.max(1000,...rows.flatMap(r=>[r.income,r.expense]));
 const y=n=>190-n/max*145;
 const line=key=>rows.map((r,i)=>`${i===0?'M':'L'}${68+i*164} ${y(r[key])}`).join(' ');
 return `<article class="panel flow">${cardHead('Fluxo financeiro','Entradas e saídas ao longo do mês','<span class="chip">Mensal</span>')}<div class="chart-legend"><span><i style="--dot:#b394ff"></i>Receitas</span><span><i style="--dot:#ed8cce"></i>Despesas</span><span class="chart-unit">Valores em R$</span></div>${state.hidden?'<div class="chart-private">Valores do gráfico ocultos</div>':`<svg class="flow-svg" viewBox="0 0 620 238" role="img" aria-label="Fluxo financeiro por semana. Valores detalhados na tabela abaixo."><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#a880ff" stop-opacity=".25"/><stop offset="100%" stop-color="#a880ff" stop-opacity="0"/></linearGradient></defs>${[0,.25,.5,.75,1].map(r=>`<path class="gridline" d="M56 ${y(max*r)}H595"/><text x="2" y="${y(max*r)+4}">${(max*r/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})}k</text>`).join('')}<path d="${line('income')} L560 190 L68 190Z" fill="url(#area)"/><path d="${line('income')}" class="income-line"/><path d="${line('expense')}" class="expense-line"/>${rows.map((r,i)=>`<circle cx="${68+i*164}" cy="${y(r.income)}" r="4" fill="#b394ff"><title>${r.label}: receitas ${money(r.income)}</title></circle><circle cx="${68+i*164}" cy="${y(r.expense)}" r="4" fill="#ed8cce"><title>${r.label}: despesas ${money(r.expense)}</title></circle><text x="${68+i*164}" y="225" text-anchor="middle">${r.label}</text>`).join('')}</svg>`}<details class="chart-details"><summary>Ver valores por semana</summary><table><thead><tr><th>Semana</th><th>Receitas</th><th>Despesas</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.label}</td><td>${val(r.income)}</td><td>${val(r.expense)}</td></tr>`).join('')}</tbody></table></details></article>`;
}
function spending(){const rows=categories(state.data),total=totals(state.data).expenses;let offset=0;return `<article class="panel spending">${cardHead('Onde você gastou','Distribuição por categoria')}<div class="donut-wrap"><svg viewBox="0 0 180 180" role="img" aria-label="Gastos por categoria, detalhados na lista abaixo"><circle cx="90" cy="90" r="69" fill="none" stroke="#252438" stroke-width="16"/>${rows.map((r,i)=>{const p=total?r.amount/total*100:0;const segment=`<circle cx="90" cy="90" r="69" pathLength="100" fill="none" stroke="${colors[i%colors.length]}" stroke-width="16" stroke-dasharray="${Math.max(0,p-1)} ${100-Math.max(0,p-1)}" stroke-dashoffset="${-offset}" transform="rotate(-90 90 90)"/>`;offset+=p;return segment;}).join('')}</svg><div class="donut-center"><small>Total de despesas</small><strong>${val(total)}</strong><span>${rows.length} categorias</span></div></div><div class="category-list">${rows.map((r,i)=>`<div><span><i style="--dot:${colors[i%colors.length]}"></i>${esc(r.name)}</span><strong>${state.hidden?'•••':`${pct(r.amount,total)}%`}</strong></div>`).join('')||'<p>Sem despesas neste período.</p>'}</div></article>`;}
function reserves(full=false){return `<article class="panel">${cardHead('Sonhos com um plano','Suas reservas',full?'':button('Ver reservas','reserves'))}${state.data.reserves.map(r=>`<div class="reserve"><div class="item-title"><span class="icon-tile violet">${icon(r.icon==='plane'?'plane':'shield')}</span><div><strong>${esc(r.name)}</strong><small>Meta de ${val(r.goal)}</small></div><span class="percent">${state.hidden?'••':pct(r.amount,r.goal)+'%'}</span></div><div class="progress" role="progressbar" aria-label="${esc(r.name)}" ${state.hidden?'':`aria-valuenow="${Math.min(100,pct(r.amount,r.goal))}" aria-valuemin="0" aria-valuemax="100"`}><span style="width:${state.hidden?0:Math.min(100,pct(r.amount,r.goal))}%"></span></div><div class="progress-caption"><strong>${val(r.amount)}</strong><span>de ${val(r.goal)}</span></div></div>`).join('')||'<p class="empty-inline">Nenhuma reserva cadastrada.</p>'}</article>`;}
function investments(full=false){const t=totals(state.data);return `<article class="panel investments">${cardHead('Dinheiro em movimento','Seus investimentos',full?'':button('Ver carteira','investments'))}<div class="investment-total"><strong>${val(t.investments)}</strong><span class="mint">Total investido</span></div>${state.data.investments.map((r,i)=>`<div class="investment-row"><span class="asset-icon ${i%2?'mint':'violet'}">${icon('chart')}</span><div><strong>${esc(r.name)}</strong><small>${esc(r.kind||'Investimento')}</small></div><b>${val(r.amount)}</b></div>`).join('')||'<p>Nenhum investimento cadastrado.</p>'}</article>`;}
function wealth(){const t=totals(state.data);return `<article class="panel wealth">${cardHead('Construindo seu amanhã','Patrimônio líquido')}<div class="wealth-total">${val(t.netWorth)}</div><div class="wealth-orbit" aria-hidden="true"><span></span><span></span><div>${icon('spark')}</div></div><div class="wealth-breakdown"><div><span>Saldo + reservas + investimentos</span><b>${val(t.balance+t.reserves+t.investments)}</b></div><div><span>Dívidas em aberto</span><b>− ${val(t.debts)}</b></div></div><small>Ativos cadastrados menos dívidas.</small></article>`;}
function debts(full=false){return `<article class="panel debts">${cardHead('Cada passo conta','Suas dívidas em um só lugar',full?'':button('Ver dívidas','debts'))}<div class="table-wrap"><table><thead><tr><th>Compromisso</th><th>Saldo devedor</th><th>Parcela</th><th>Juros a.m.</th><th>Prioridade</th></tr></thead><tbody>${state.data.debts.map(d=>`<tr><td><span class="table-name">${icon('card')}${esc(d.name)}</span></td><td>${val(d.amount)}</td><td>${val(d.installment)}</td><td>${state.hidden?'••':d.interest.toLocaleString('pt-BR')+'%'}</td><td><span class="priority ${d.priority==='Alta'?'high':''}">${esc(d.priority)}</span></td></tr>`).join('')||'<tr><td colspan="5">Nenhuma dívida cadastrada neste período.</td></tr>'}</tbody></table></div></article>`;}
function insight(full=false){return `<article class="panel insight"><div class="insight-label">${icon('spark')} LUNA INTELLIGENCE <span>${isDemo?'EXEMPLO':'IA'}</span></div><h2>Mais clareza.<br><span>Melhores próximos passos.</span></h2><p>${esc(state.data.insight||'Ainda não há um insight para este período.')}</p><div class="insight-footer">${full?'<small>Insights são informativos. Considere seu contexto antes de tomar decisões.</small>':button('Explorar meu insight','insight')}${icon('spark')}</div></article>`;}
function transactions(){return `<article class="panel transactions">${cardHead('Todas as movimentações',monthLabel(state.month))}<div class="filters"><label class="search">${icon('search')}<input id="search" type="search" placeholder="Buscar movimentação…" aria-label="Buscar movimentação" value="${esc(state.search)}"></label><select id="type" aria-label="Tipo de movimentação"><option value="all">Todos os tipos</option><option value="income">Receitas</option><option value="expense">Despesas</option></select></div><div id="transaction-rows"></div></article>`;}
function transactionRows(){const rows=state.data.transactions.filter(t=>(state.type==='all'||state.type===t.type)&&`${t.name} ${t.category}`.toLocaleLowerCase('pt-BR').includes(state.search.toLocaleLowerCase('pt-BR'))).sort((a,b)=>b.date.localeCompare(a.date));document.querySelector('#transaction-rows').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Data</th><th>Valor</th></tr></thead><tbody>${rows.map(t=>`<tr><td><span class="table-name ${t.type==='income'?'mint':''}">${icon(t.type==='income'?'up':'down')}${esc(t.name)}</span></td><td>${esc(t.category)}</td><td>${t.date.split('-').reverse().join('/')}</td><td class="${t.type==='income'?'mint':'pink'}">${t.type==='income'?'+':'−'} ${val(t.amount)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhuma movimentação encontrada.</td></tr>'}</tbody></table></div><p class="table-count">${rows.length} movimentações</p>`;}
function settings(){return `<article class="panel settings-panel">${cardHead('Seu espaço, do seu jeito','Conexões e privacidade')}<div class="connection"><span class="icon-tile violet">${icon('shield')}</span><div><h3>${isDemo?'Você está no modo demonstração':'Supabase conectado'}</h3><p>${isDemo?'Explore o dashboard com dados fictícios. Nenhuma conta bancária está conectada.':'Dados carregados apenas para o usuário autenticado.'}</p></div><span class="chip">${isDemo?'Demo':'Ativo'}</span></div><p>O botão de olho no topo oculta os valores. A exportação gera um arquivo CSV das movimentações do período selecionado.</p><p>${isDemo?'Para ativar dados reais, siga o README do projeto e configure a conexão com Supabase.':'Sua sessão é mantida apenas na memória desta aba. Ao recarregar, será necessário entrar novamente.'}</p>${!isDemo?'<button id="logout" class="outline-button">Sair da conta</button>':''}</article>`;}
function login(){return `<section class="panel login">${cardHead('Bem-vinda ao seu espaço','Entre para acessar suas finanças com segurança.')}<form id="login"><label>E-mail<input type="email" name="email" autocomplete="username" required></label><label>Senha<input type="password" name="password" autocomplete="current-password" required></label><button class="primary-button" type="submit">Entrar</button><p id="login-error" role="alert"></p></form></section>`;}
function render(){
 if(!document.querySelector('#content'))return;
 const label=nav.find(n=>n[0]===state.page)?.[2]||'Configurações';
 document.querySelector('#breadcrumb-title').textContent=label;
 document.querySelector('#page-title').innerHTML=state.page==='overview'?'Seu dinheiro. Seu futuro<span>.</span>':esc(label);
 document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===state.page);if(a.dataset.page===state.page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 document.querySelector('#export').disabled=!state.data||state.loading;
 const content=document.querySelector('#content');
 if(!isDemo&&!hasSession()){content.innerHTML=login();document.querySelector('#login').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,btn=form.querySelector('button');btn.disabled=true;try{await signIn(form.email.value,form.password.value);form.reset();await refresh();}catch(error){document.querySelector('#login-error').textContent=error.message;}finally{btn.disabled=false;}});return;}
 if(state.loading){content.innerHTML='<div class="loading" role="status"><span></span>Atualizando sua visão financeira…</div>';return;}
 if(state.error){content.innerHTML=`<div class="panel empty"><h2>Não foi possível carregar</h2><p>${esc(state.error)}</p><button id="retry" class="primary-button">Tentar novamente</button></div>`;document.querySelector('#retry').onclick=refresh;return;}
 if(state.page==='settings'){content.innerHTML=settings();const logout=document.querySelector('#logout');if(logout)logout.onclick=async()=>{try{await signOut();}catch{toast('Sessão local encerrada.');}state.data=null;render();};return;}
 if(!state.data){content.innerHTML='<div class="panel empty"><h2>Um novo começo</h2><p>Ainda não há dados para este mês. Escolha outro período para continuar.</p></div>';return;}
 const pages={overview:()=>`${kpis()}<div class="analytics-grid">${flowChart()}${spending()}</div><div class="goals-grid">${reserves()}${investments()}${wealth()}</div><div class="bottom-grid">${debts()}${insight()}</div>`,transactions,debts:()=>`${debts(true)}<div class="section-note">Total em aberto: <strong>${val(totals(state.data).debts)}</strong></div>`,reserves:()=>`<div class="detail-grid">${reserves(true)}${wealth()}</div>`,investments:()=>`<div class="detail-grid">${investments(true)}${wealth()}</div>`,insight:()=>`<div class="detail-grid">${insight(true)}${reserves()}</div>`};
 content.innerHTML=pages[state.page]();
 if(state.page==='transactions'){transactionRows();document.querySelector('#type').value=state.type;document.querySelector('#search').oninput=e=>{state.search=e.target.value;transactionRows();};document.querySelector('#type').onchange=e=>{state.type=e.target.value;transactionRows();};}
}
let requestId=0;
async function refresh(){const id=++requestId;state.loading=true;state.error=null;state.data=null;render();try{const data=await loadDashboard(state.month);if(id===requestId)state.data=data;}catch(error){if(id===requestId)state.error=error.message;}finally{if(id===requestId){state.loading=false;render();}}}
function toast(message){const element=document.querySelector('#toast');element.textContent=message;element.hidden=false;setTimeout(()=>element.hidden=true,3500);}
function exportCsv(){if(!state.data)return;if(state.hidden){toast('Mostre os valores antes de exportar.');return;}const url=URL.createObjectURL(new Blob([toCsv(state.data.transactions)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`luna-movimentacoes-${state.month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Exportação do período preparada.');}
shell();
refresh();
